---
- name: Gather Service Information
  become: true
  service_facts:
- name: Service Monitoring Sanity Test
  when:
    - ansible_service_mgr != "systemd"
    - flb_inputs.services is defined
    - flb_inputs.services | length > 0
  fail:
    msg: 'SystemD Service "{{ item }}" is marked for monitoring, but target system init is "{{ ansible_service_mgr }}"! Service will not be monitored.'
  with_items: '{{ flb_inputs.services }}'
  ignore_errors: yes
- name: Install td-agent-bit from .deb
  when: >- 
      not flb_build_force | default(false) 
      and (
        ( ansible_distribution | lower ) == 'ubuntu' and 
        ( ansible_distribution_major_version | int ) is divisibleby 2 and 
        ( ansible_distribution_major_version | int ) > 14 
      )
      or (
        ( ansible_distribution | lower ) == 'debian' and 
        ( ansible_distribution_release | lower ) in ['stretch', 'jessie'] 
      )
  block:
    - name: Add td-agent-bit apt-key
      become: true
      apt_key:
        url: https://packages.fluentbit.io/fluentbit.key
        state: present
    - name: Add td-agent-bit apt repository
      become: true
      apt_repository:
        repo: >-
          deb https://packages.fluentbit.io/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}
          {{ ansible_distribution_release | lower }}
          main
        state: present
        filename: td-agent-bit
        update_cache: true
    - name: Install td-agent-bit .deb package
      become: true
      package:
        name: td-agent-bit
        state: present
        update_cache: true
      notify: Restart td-agent-bit
      tags: ['install']
      register: td_agent_installed
    - name: Ensure td-agent-bit Service is enabled
      become: true
      service:
        name: td-agent-bit
        enabled: yes
    - name: Gather Service Information
      become: true
      service_facts:
- name: Install td-agent-bit from .rpm
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - not flb_build_force | default(false)
  block:
    - name: Add td-agent-bit YUM Repository
      become: true
      yum_repository:
        name: TD_Agent_Bit
        baseurl: http://packages.fluentbit.io/centos/7
        gpgcheck: true
        gpgkey: http://packages.fluentbit.io/fluentbit.key
        description: Fluent bit repo
        enabled: true
    - name: Install td-agent-bit .rpm package
      become: true
      package:
        name: td-agent-bit
        state: present
      notify: Restart td-agent-bit
      register: td_agent_installed
      tags: ['install']
    - name: Ensure td-agent-bit Service is enabled
      become: true
      service:
        name: td-agent-bit
        enabled: yes
    - name: Gather Service Information
      become: true
      service_facts:
- name: Compile td-agent-bit From Sources [ FALLBACK ]
  when: >-
    flb_build_force | default(false) or 
    ((
      td_agent_installed is not defined or 
      td_agent_installed.skipped or 
      td_agent_installed.failed ) and 
    ( 
      'td-agent-bit' not in ansible_facts.services and 
      'td-agent-bit.service' not in ansible_facts.services 
    ))
  block:
      - name: Install Build Dependencies
        when: ansible_os_family == "Debian"
        become: true
        apt:
          update_cache: true
          state: present
          pkg:
          - build-essential
          - "{{ (( ansible_distribution | lower ) == 'ubuntu' and ( ansible_distribution_major_version | int) >= 16) | ternary('cmake','cmake3') }}"
          - bison
          - libbison-dev
          - flex
          - libfl-dev
          - pkg-config
          - zlibc
          - zlib1g-dev
          - libpq-dev
          - doxygen
          - libgtest-dev
          - libevent-dev
      - name: Uninstall td-agent-bit System Package, if installed
        become: true
        package:
          name: td-agent-bit
          state: absent
      - name: Install Build Dependencies
        when: ansible_os_family == "RedHat"
        become: true
        yum:
          name:
            - "@Development tools"
            - cmake
          state: present
      - name: Create Build Directory
        become: true
        file:
          path: "{{ flb_build_dir }}"
          state: directory
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          mode: 0775
      - name: Download td-agent-bit Sources
        become: true
        unarchive:
          src: https://fluentbit.io/releases/{{ flb_build_vers.split(".")[0] }}.{{ flb_build_vers.split(".")[1] }}/fluent-bit-{{ flb_build_vers }}.tar.gz
          dest: "{{ flb_build_dir }}"
          remote_src: yes
          owner: "{{ ansible_user }}"
      - name: Configure td-agent-bit
        command:
          chdir: "{{ flb_build_dir }}/fluent-bit-{{ flb_build_vers }}"
          argv:
            - /usr/bin/cmake
            - "{{ flb_build_dir }}/fluent-bit-{{ flb_build_vers }}"
            - "-DFLB_JEMALLOC=ON"
            - "-DFLB_TLS=ON"
            - "-DFLB_BUFFERING=ON"
            - "-DFLB_WITHOUT_EXAMPLES=ON"
            - "-DFLB_TD=ON"
            - "-DFLB_IN_SYSTEMD={{ ansible_service_mgr | lower == 'systemd' | ternary('ON','OFF') }}"
            - "-DCMAKE_INSTALL_SYSCONFDIR={{ flb_sys_conf_dir }}"
            - "-DCMAKE_INSTALL_FULL_BINDIR={{ flb_build_install_prefix }}/bin"
            - "-DCMAKE_INSTALL_PREFIX={{ flb_build_install_prefix }}"
      - name: Compile td-agent-bit
        make:
          chdir: "{{ flb_build_dir }}/fluent-bit-{{ flb_build_vers }}"
          target: all
          params:
            NUM_THREADS: 2
      - name: Install td-agent-bit
        become: true
        make:
          chdir: "{{ flb_build_dir }}/fluent-bit-{{ flb_build_vers }}"
          target: install
      - name: Gather Service Information
        become: true
        service_facts:
      - name: Stat td-agent-bin Upstart Service File
        become: true
        stat:
          path: "{{ flb_upstart_script }}"
        register: flb_upstart_script_stat
        when: ansible_service_mgr | lower == 'upstart'
      - name: Manually Install Upstart Script
        when:
          - flb_upstart_script_stat.stat is not defined or not flb_upstart_script_stat.stat.exists
        block:
          - name: Find td-agent-bit binary location
            shell: "which td-agent-bit | tr -d '[:space:]'"
            register: flb_binary_location
          - name: Set flb_binary Fact
            set_fact:
              flb_binary: "{{ flb_binary_location.stdout }}"
          - name: Template out td-agent-bit upstart file if needed
            become: true
            template:
              src: 'init/td-agent-bit.conf.j2'
              dest: '/etc/init/td-agent-bit.conf'
              mode: 0644
              owner: root
            notify: Restart td-agent-bit
          - name: Reload initctl Configuration
            become: true
            command: "initctl reload-configuration"
      - name: Gather Service Information
        become: true
        service_facts:
- name: Ensure td-agent-bit Service is enabled and started
  become: true
  when:
    - "'td-agent-bit' in ansible_facts.services or 'td-agent-bit.service' in ansible_facts.services"
  service:
    name: td-agent-bit
    enabled: yes
    state: started
- name: Install logrotate
  when:
    - flb_inputs.files is defined and flb_inputs.files|length > 0
  become: true
  package:
    name: logrotate
    state: present